### ISSUE TITLE
GTHMC implementation

### ISSUE THREAD

**Issue by madanh** [aki-nishimura/discontinuous-hmc#1]
Dear Dr.  Nishimura,

Please accept my apologies for using github issues as a communications channel.

I've recently read your paper on GTHMC and it seems that it could help in my problem which involves sampling from a multimodal distribution. I cannot pretend to understand all the mathematics of GTHMC paper, let alone implement it.

Given this I kindly ask you to share your GTHMC implementation if that is a possibility.

Sincerely,

Hennadii Madan

**Comment by aki-nishimura** [comment]
Thank you for your interest in my work, but as you say Github issues are **not** meant to be used as a communication channel like this, especially for topics unrelated to the repository.... In the future, please just email at my UCLA email (if you could not easily find it, then I should fix that problem). I am just writing this out explicitly to prevent other people doing the same. 

In any case, I wrote a matlab code for GTHMC before I learned how to keep things organized via git & other good software engineering practices and the code is very messy.... I am revising the manuscript and plan to post it online at some point. In the mean time, I suggest you look into using parallel tempering (it can be used in conjunction with HMC) if you have problems with multi-modal densities.
